name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          architecture: 'x64'
          cache: pip
          cache-dependency-path: poetry.lock

      - name: Install poetry
        run: pipx install --python python3.11 poetry==1.8.2

      - name: Install dependencies
        run: poetry install --no-dev

      - name: Publish
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_PASSWORD }}
        run: |
          poetry config pypi-token.pypi $PYPI_TOKEN
          poetry publish --build
